// ================================================================
// CRAFTORA – Comprehensive Realistic Handmade Products Dataset
// 96 products covering all 8 e-commerce categories (12 products per category)
// All images hosted locally under /images/products/ with 100% unique hashes
// ================================================================

export const initialAllProducts = [
  {
    "id": 1,
    "name": "Handloom Cotton Kurta with Mirror Work",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "Classic mens kurta handwoven from premium cotton with hand-stitched mirror work detailing on collar and cuffs.",
    "price": 1199.0,
    "original_price": 1498.75,
    "image": "/images/products/men-handloom-kurta.jpg",
    "material": "Handloom cotton with mirror embroidery",
    "dimensions": "Sizes: S, M, L, XL, XXL",
    "care_instructions": "Gentle machine wash cold. Iron on reverse.",
    "stock_quantity": 12,
    "rating": 4.7,
    "is_customizable": true
  },
  {
    "id": 2,
    "name": "Shantiniketan Embossed Leather Folio",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Handcrafted Shantiniketan embossed leather folio featuring traditional floral motifs, crafted using vegetable dyes.",
    "price": 1249.0,
    "original_price": null,
    "image": "/images/products/men-leather-folio.jpg",
    "material": "Vegetable-tanned goat leather",
    "dimensions": "32cm x 24cm",
    "care_instructions": "Condition with leather wax every 6 months.",
    "stock_quantity": 9,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 3,
    "name": "Hand-Embroidered Kashmiri Aari Waistcoat",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Traditional handcrafted Kashmiri men's waistcoat featuring intricate floral Aari thread embroidery on raw silk.",
    "price": 2499.0,
    "original_price": 3123.75,
    "image": "/images/products/men-kashmiri-waistcoat.jpg",
    "material": "Pure raw silk with wool Aari embroidery",
    "dimensions": "Sizes: S, M, L, XL",
    "care_instructions": "Dry clean only. Store in cotton bag.",
    "stock_quantity": 8,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 4,
    "name": "Handcrafted Leather & Brass Bracelet",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Braided genuine leather bracelet with hand-hammered brass medallion stamped with traditional motifs.",
    "price": 599.0,
    "original_price": null,
    "image": "/images/products/men-leather-brass-bracelet.jpg",
    "material": "Vegetable-tanned leather & brass",
    "dimensions": "Adjustable 18\u201322cm",
    "care_instructions": "Wipe clean with dry cloth.",
    "stock_quantity": 14,
    "rating": 4.7,
    "is_customizable": true
  },
  {
    "id": 5,
    "name": "Hand-Woven Khadi Stole for Men",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Soft hand-spun khadi cotton stole with natural vegetable-dyed stripe border.",
    "price": 750.0,
    "original_price": 937.5,
    "image": "/images/products/men-khadi-stole.jpg",
    "material": "Pure hand-spun khadi cotton",
    "dimensions": "200cm x 55cm",
    "care_instructions": "Gentle hand wash cold.",
    "stock_quantity": 10,
    "rating": 4.5,
    "is_customizable": false
  },
  {
    "id": 6,
    "name": "Rajasthani Mojari Hand-Stitched Leather Shoes",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "Authentic leather mojari footwear hand-stitched with colorful thread and traditional motifs.",
    "price": 1499.0,
    "original_price": null,
    "image": "/images/products/men-rajasthani-mojari.jpg",
    "material": "Genuine camel leather",
    "dimensions": "Sizes: UK 7 to 11",
    "care_instructions": "Keep away from water. Use leather polish.",
    "stock_quantity": 15,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 7,
    "name": "Organic Indigo Dabu Block Print Shirt",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "Pure cotton men's casual shirt dyed in natural indigo vats using age-old Dabu mud-resist block technique.",
    "price": 1350.0,
    "original_price": 1687.5,
    "image": "/images/products/men-dabu-block-shirt.jpg",
    "material": "100% organic cotton",
    "dimensions": "Sizes: S, M, L, XL",
    "care_instructions": "Wash separately in cold water with mild detergent.",
    "stock_quantity": 18,
    "rating": 4.6,
    "is_customizable": true
  },
  {
    "id": 8,
    "name": "Hand-Carved Teakwood Cufflinks & Box Set",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Square teakwood cufflinks brass-inlaid with geometric patterns, stored in a hand-carved mini chest.",
    "price": 899.0,
    "original_price": null,
    "image": "/images/products/men-teakwood-cufflinks.jpg",
    "material": "Reclaimed teakwood & brass",
    "dimensions": "Cufflinks: 1.5cm, Box: 8cm x 5cm",
    "care_instructions": "Wipe wood with dry microfiber cloth.",
    "stock_quantity": 11,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 9,
    "name": "Chanderi Silk Men's Dupatta with Zari Border",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Elegant lightweight Chanderi silk stole featuring woven gold zari border for festive occasions.",
    "price": 1699.0,
    "original_price": 2123.75,
    "image": "/images/products/men-chanderi-dupatta.jpg",
    "material": "Chanderi silk-cotton blend with gold zari",
    "dimensions": "230cm x 60cm",
    "care_instructions": "Dry clean recommended.",
    "stock_quantity": 7,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 10,
    "name": "Handcrafted Brass Buckle Leather Belt",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Full-grain leather belt paired with a hand-cast solid brass buckle stamped with mandala art.",
    "price": 1099.0,
    "original_price": null,
    "image": "/images/products/men-brass-leather-belt.jpg",
    "material": "Full-grain cowhide leather & brass",
    "dimensions": "Length: 32 - 42 inches",
    "care_instructions": "Condition leather periodically.",
    "stock_quantity": 20,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 11,
    "name": "Pashmina Wool Muffler with Sozni Stitch",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 10,
    "artisan_name": "Tenzing Norbu",
    "description": "Warm Himalayan sheep wool muffler delicately decorated with hand-embroidered Sozni needlework.",
    "price": 2899.0,
    "original_price": 3623.75,
    "image": "/images/products/men-pashmina-muffler.jpg",
    "material": "100% Himalayan Pashmina Wool",
    "dimensions": "180cm x 35cm",
    "care_instructions": "Dry clean only. Store with cedar balls.",
    "stock_quantity": 6,
    "rating": 5.0,
    "is_customizable": false
  },
  {
    "id": 12,
    "name": "Kolhapuri Hand-Carved Leather Sandals",
    "category_id": 1,
    "category": "Men",
    "category_name": "Men",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Traditional Kolhapuri leather chappal with braided strap detailing and sturdy hand-stitched soles.",
    "price": 1299.0,
    "original_price": null,
    "image": "/images/products/men-kolhapuri-sandals.jpg",
    "material": "Tanned buffalo leather",
    "dimensions": "Sizes: UK 6 to 11",
    "care_instructions": "Apply mustard oil occasionally for softness.",
    "stock_quantity": 13,
    "rating": 4.6,
    "is_customizable": false
  },
  {
    "id": 13,
    "name": "Pure Kanjeevaram Silk Saree with Zari Motif",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Lustrous mulberry silk saree handwoven in Kanchipuram with rich gold zari peacock border.",
    "price": 4999.0,
    "original_price": 6248.75,
    "image": "/images/products/women-kanjeevaram-saree.jpg",
    "material": "Pure Mulberry Silk & Gold Zari",
    "dimensions": "Saree: 5.5m + 0.8m Blouse",
    "care_instructions": "Dry clean only. Store in muslin cloth.",
    "stock_quantity": 6,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 14,
    "name": "Hand-Block Printed Chanderi Cotton Dupatta",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "Breathable lightweight Chanderi fabric adorned with Bagru block floral prints and zari trim.",
    "price": 899.0,
    "original_price": null,
    "image": "/images/products/women-chanderi-dupatta.jpg",
    "material": "Chanderi silk-cotton",
    "dimensions": "2.4m x 0.9m",
    "care_instructions": "Gentle hand wash in cold water.",
    "stock_quantity": 18,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 15,
    "name": "Chikankari Embroidered Georgette Kurti",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Ethereal Lucknowi Chikankari embroidered kurti with intricate Shadow and Bakhiya stitches.",
    "price": 1899.0,
    "original_price": 2373.75,
    "image": "/images/products/women-chikankari-kurti.jpg",
    "material": "Faux georgette with cotton thread",
    "dimensions": "Sizes: XS to XXL",
    "care_instructions": "Hand wash cold or dry clean.",
    "stock_quantity": 12,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 16,
    "name": "Phulkari Hand-Embroidered Velvet Shawl",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Vibrant Punjabi Phulkari floral thread embroidery on rich maroon velvet base fabric.",
    "price": 2799.0,
    "original_price": null,
    "image": "/images/products/women-phulkari-shawl.jpg",
    "material": "Velvet fabric with rayon thread",
    "dimensions": "2.2m x 1.0m",
    "care_instructions": "Dry clean only.",
    "stock_quantity": 9,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 17,
    "name": "Bandhani Tie & Dye Mulberry Silk Dupatta",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "Traditional Rajasthani tie-and-dye dupatta featuring thousands of tiny hand-tied dots.",
    "price": 1599.0,
    "original_price": 1998.75,
    "image": "/images/products/women-bandhani-dupatta.jpg",
    "material": "100% Pure Mulberry Silk",
    "dimensions": "2.5m x 1.0m",
    "care_instructions": "Dry clean only. Preserve roll crush.",
    "stock_quantity": 11,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 18,
    "name": "Banarasi Brocade Potli Bag & Saree Belt",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Coordinated festive set featuring a woven zari potli handbag and matching embroidered waist belt.",
    "price": 1299.0,
    "original_price": null,
    "image": "/images/products/women-banarasi-potli-belt.jpg",
    "material": "Banarasi silk brocade & metallic zari",
    "dimensions": "Potli: 20cm x 18cm, Belt: Adjustable",
    "care_instructions": "Spot clean only.",
    "stock_quantity": 14,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 19,
    "name": "Kalamkari Hand-Painted Cotton Saree",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Srikalahasti style hand-painted saree depicting mythological lore painted with natural dyes.",
    "price": 3499.0,
    "original_price": 4373.75,
    "image": "/images/products/women-kalamkari-saree.jpg",
    "material": "100% Handloom Cotton",
    "dimensions": "Saree: 5.5m + Blouse",
    "care_instructions": "Dry clean recommended.",
    "stock_quantity": 5,
    "rating": 5.0,
    "is_customizable": true
  },
  {
    "id": 20,
    "name": "Sambalpuri Ikat Weave Cotton Kurta Set",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Authentic Odisha double-ikat weave cotton kurti paired with matching plain palazzo pants.",
    "price": 2199.0,
    "original_price": null,
    "image": "/images/products/women-ikat-kurta-set.jpg",
    "material": "Pure Handloom Ikat Cotton",
    "dimensions": "Sizes: S, M, L, XL",
    "care_instructions": "Gentle wash cold separately.",
    "stock_quantity": 10,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 21,
    "name": "Hand-Embroidered Zardozi Velvet Jacket",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Royal festive layering jacket handcrafted with heavy gold zari, pearls, and metallic wire threadwork.",
    "price": 3899.0,
    "original_price": 4873.75,
    "image": "/images/products/women-zardozi-jacket.jpg",
    "material": "Rich Silk Velvet & Zardozi Wire",
    "dimensions": "Sizes: S, M, L",
    "care_instructions": "Dry clean only.",
    "stock_quantity": 4,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 22,
    "name": "Maheshwari Handloom Silk Cotton Saree",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Classic Maheshwari saree featuring reversible zari border and traditional check pattern weave.",
    "price": 2699.0,
    "original_price": null,
    "image": "/images/products/women-maheshwari-saree.jpg",
    "material": "Silk-Cotton Blend",
    "dimensions": "Saree: 5.5m + Blouse",
    "care_instructions": "Dry clean for first wash.",
    "stock_quantity": 8,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 23,
    "name": "Pochampally Ikat Weave Cotton Dupatta",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Geometric ikat pattern handwoven by Telangana master weavers using resist-dyed cotton yarn.",
    "price": 1199.0,
    "original_price": 1498.75,
    "image": "/images/products/women-pochampally-dupatta.jpg",
    "material": "100% Mercerized Cotton",
    "dimensions": "2.4m x 0.9m",
    "care_instructions": "Hand wash with mild liquid detergent.",
    "stock_quantity": 15,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 24,
    "name": "Jamdani Hand-Woven Muslin Cotton Saree",
    "category_id": 2,
    "category": "Women",
    "category_name": "Women",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Featherlight Bengal Jamdani saree with extra-weft motif weaving that floats on sheer fabric.",
    "price": 3299.0,
    "original_price": null,
    "image": "/images/products/women-jamdani-saree.jpg",
    "material": "Fine Muslin Cotton",
    "dimensions": "Saree: 5.5m + Blouse",
    "care_instructions": "Hand wash with care or dry clean.",
    "stock_quantity": 7,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 25,
    "name": "Channapatna Lacquerwood Stacking Rings",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 6,
    "artisan_name": "Balram Patra",
    "description": "Classic eco-friendly wooden stacking tower painted with non-toxic vegetable dyes.",
    "price": 599.0,
    "original_price": 748.75,
    "image": "/images/products/kids-channapatna-stacking-rings.jpg",
    "material": "Wrightia tinctoria wood & organic lacquer",
    "dimensions": "18cm height",
    "care_instructions": "Wipe clean with dry cloth.",
    "stock_quantity": 20,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 26,
    "name": "Handmade Organic Cotton Elephant Soft Toy",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Plush elephant stuffed toy hand-stitched from GOTS certified organic cotton fabric.",
    "price": 699.0,
    "original_price": null,
    "image": "/images/products/kids-cotton-elephant-toy.jpg",
    "material": "Organic Cotton & Recycled Fiberfill",
    "dimensions": "22cm length",
    "care_instructions": "Machine washable gentle cycle.",
    "stock_quantity": 15,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 27,
    "name": "Hand-Painted Madhubani Wooden Blocks",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 8,
    "artisan_name": "Sunita Devi",
    "description": "Set of 12 solid wooden building blocks hand-painted with colorful animal figures.",
    "price": 899.0,
    "original_price": 1123.75,
    "image": "/images/products/kids-madhubani-wooden-blocks.jpg",
    "material": "Natural Mango wood & child-safe paint",
    "dimensions": "Each block: 4cm cube",
    "care_instructions": "Wipe with soft cloth.",
    "stock_quantity": 12,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 28,
    "name": "Kondapalli Wooden Dancing Doll Toy",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 6,
    "artisan_name": "Balram Patra",
    "description": "Traditional Andhra bobblehead dancing lady toy handcrafted from light softwood.",
    "price": 749.0,
    "original_price": null,
    "image": "/images/products/kids-kondapalli-dancing-doll.jpg",
    "material": "Tella Poniki wood & natural colors",
    "dimensions": "25cm height",
    "care_instructions": "Handle with care.",
    "stock_quantity": 14,
    "rating": 4.7,
    "is_customizable": true
  },
  {
    "id": 29,
    "name": "Hand-Knitted Wool Baby Booties & Beanie",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 10,
    "artisan_name": "Tenzing Norbu",
    "description": "Ultra-soft baby winter booties and matching bear-ear beanie hand-knitted from merino wool.",
    "price": 649.0,
    "original_price": 811.25,
    "image": "/images/products/kids-wool-baby-booties.jpg",
    "material": "100% Soft Merino Wool",
    "dimensions": "0 - 12 Months size",
    "care_instructions": "Hand wash cold gently.",
    "stock_quantity": 18,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 30,
    "name": "Channapatna Wooden Push Toy Car",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 6,
    "artisan_name": "Balram Patra",
    "description": "Smooth rolling toy car turned on traditional wooden lathe without sharp edges.",
    "price": 499.0,
    "original_price": null,
    "image": "/images/products/kids-channapatna-toy-car.jpg",
    "material": "Lacquerwood",
    "dimensions": "14cm x 8cm",
    "care_instructions": "Wipe with dry cloth.",
    "stock_quantity": 22,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 31,
    "name": "Eco Bamboo Xylophone & Mallet for Toddlers",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 6,
    "artisan_name": "Balram Patra",
    "description": "Handcrafted bamboo musical xylophone tuned to produces soft melodic tones.",
    "price": 999.0,
    "original_price": 1248.75,
    "image": "/images/products/kids-bamboo-xylophone.jpg",
    "material": "Natural Bamboo & Teak mallets",
    "dimensions": "30cm x 15cm",
    "care_instructions": "Keep dry.",
    "stock_quantity": 11,
    "rating": 4.7,
    "is_customizable": true
  },
  {
    "id": 32,
    "name": "Kinnal Handcrafted Wooden Animal Set",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 6,
    "artisan_name": "Balram Patra",
    "description": "Set of 5 hand-carved wooden jungle animal figures decorated with natural pigments.",
    "price": 1199.0,
    "original_price": null,
    "image": "/images/products/kids-kinnal-wooden-animals.jpg",
    "material": "Kinnal softwood & natural paste",
    "dimensions": "Average size: 10cm",
    "care_instructions": "Wipe clean gently.",
    "stock_quantity": 9,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 33,
    "name": "Hand-Stitched Patchwork Baby Quilt",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Reversible soft cotton baby blanket stuffed with pure cotton battings.",
    "price": 1299.0,
    "original_price": 1623.75,
    "image": "/images/products/kids-patchwork-baby-quilt.jpg",
    "material": "100% Cotton fabric & fill",
    "dimensions": "110cm x 90cm",
    "care_instructions": "Machine wash cold gentle.",
    "stock_quantity": 10,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 34,
    "name": "Natural Clay Bhatukali Mini Cooking Set",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Traditional 10-piece miniature kitchen play set hand-moulded from red terracotta clay.",
    "price": 549.0,
    "original_price": null,
    "image": "/images/products/kids-terracotta-mini-cookware.jpg",
    "material": "Terracotta Clay",
    "dimensions": "Miniature cookware pieces",
    "care_instructions": "Do not drop on hard surfaces.",
    "stock_quantity": 16,
    "rating": 4.6,
    "is_customizable": true
  },
  {
    "id": 35,
    "name": "Soft Handloom Cotton Baby Swaddle Cloth",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "Set of 2 breathable pre-washed cotton muslin swaddle wraps with block prints.",
    "price": 799.0,
    "original_price": 998.75,
    "image": "/images/products/kids-cotton-swaddle-cloth.jpg",
    "material": "100% Muslin Cotton",
    "dimensions": "100cm x 100cm",
    "care_instructions": "Machine wash warm.",
    "stock_quantity": 25,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 36,
    "name": "Channapatna Wooden Bowling Pins Set",
    "category_id": 3,
    "category": "Kids",
    "category_name": "Kids",
    "artisan_id": 6,
    "artisan_name": "Balram Patra",
    "description": "6 vibrant colorful wooden pins and 2 balls for fun indoor bowling play.",
    "price": 1099.0,
    "original_price": null,
    "image": "/images/products/kids-channapatna-bowling-pins.jpg",
    "material": "Seasoned Wood & Lacquer",
    "dimensions": "Pin height: 16cm",
    "care_instructions": "Wipe with clean cloth.",
    "stock_quantity": 13,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 37,
    "name": "Hand-Painted Blue Pottery Ceramic Vase",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Jaipur blue pottery necked flower vase featuring hand-painted cobalt floral arabesques.",
    "price": 1499.0,
    "original_price": 1873.75,
    "image": "/images/products/home-blue-pottery-vase.jpg",
    "material": "Quartz powder, glass & natural oxide",
    "dimensions": "24cm height x 12cm diameter",
    "care_instructions": "Wipe clean with soft damp cloth.",
    "stock_quantity": 10,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 38,
    "name": "Macrame Hand-Woven Wall Hanging",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Bohemian geometric wall tapestry knotted from natural unbleached cotton cord.",
    "price": 1299.0,
    "original_price": null,
    "image": "/images/products/home-macrame-wall-hanging.jpg",
    "material": "100% Natural Cotton Rope & Driftwood",
    "dimensions": "65cm length x 40cm width",
    "care_instructions": "Gentle shake to dust. Do not wash.",
    "stock_quantity": 14,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 39,
    "name": "Hand-Carved Teakwood Coaster Set",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Set of 6 square wooden drink coasters brass-inlaid with traditional lotus motif.",
    "price": 799.0,
    "original_price": 998.75,
    "image": "/images/products/home-teakwood-coaster-set.jpg",
    "material": "Teakwood with brass wire inlay",
    "dimensions": "10cm x 10cm each",
    "care_instructions": "Wipe dry after spills. Oil wood occasionally.",
    "stock_quantity": 20,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 40,
    "name": "Terracotta Hand-Moulded Table Lamp",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Earthen terracotta lamp base accompanied by a hand-block printed cotton drum shade.",
    "price": 2199.0,
    "original_price": null,
    "image": "/images/products/home-terracotta-table-lamp.jpg",
    "material": "Natural Baked Clay & Cotton Shade",
    "dimensions": "Total Height: 45cm",
    "care_instructions": "Dust shade with soft brush. B22 bulb required.",
    "stock_quantity": 8,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 41,
    "name": "Brass Dhokra Tribal Candle Holder",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Lost-wax cast brass candle holder depicting a pair of tribal musicians.",
    "price": 1199.0,
    "original_price": 1498.75,
    "image": "/images/products/home-dhokra-candle-holder.jpg",
    "material": "Cast Brass",
    "dimensions": "18cm x 12cm",
    "care_instructions": "Clean with brass polish.",
    "stock_quantity": 12,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 42,
    "name": "Hand-Block Printed Cotton Table Runner",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "100% cotton table runner printed with traditional Mughal floral bootis and tassels.",
    "price": 899.0,
    "original_price": null,
    "image": "/images/products/home-block-print-table-runner.jpg",
    "material": "Pure Heavy Cotton Canvas",
    "dimensions": "180cm x 35cm",
    "care_instructions": "Cold machine wash. Iron on reverse.",
    "stock_quantity": 16,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 43,
    "name": "Bidriware Silver Inlaid Marble Coasters",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Set of 4 black Bidri alloy coasters with fine silver floral wire inlay.",
    "price": 1699.0,
    "original_price": 2123.75,
    "image": "/images/products/home-bidriware-marble-coasters.jpg",
    "material": "Zinc Alloy & Pure Silver Inlay",
    "dimensions": "9cm diameter",
    "care_instructions": "Apply coconut oil to maintain shine.",
    "stock_quantity": 9,
    "rating": 5.0,
    "is_customizable": true
  },
  {
    "id": 44,
    "name": "Handloom Jute & Cotton Braided Floor Rug",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Reversible eco-friendly area floor mat hand-braided from natural jute and cotton yarn.",
    "price": 1999.0,
    "original_price": null,
    "image": "/images/products/home-jute-braided-rug.jpg",
    "material": "70% Jute, 30% Cotton",
    "dimensions": "120cm x 80cm",
    "care_instructions": "Vacuum regularly. Spot clean with damp cloth.",
    "stock_quantity": 11,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 45,
    "name": "Madhubani Hand-Painted Ceramic Tea Cups",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 8,
    "artisan_name": "Sunita Devi",
    "description": "Set of 6 ceramic kulhad style tea cups decorated with colorful Madhubani fish motifs.",
    "price": 1199.0,
    "original_price": 1498.75,
    "image": "/images/products/home-madhubani-ceramic-cups.jpg",
    "material": "Stoneware Ceramic",
    "dimensions": "Capacity: 180ml each",
    "care_instructions": "Microwave & Dishwasher safe.",
    "stock_quantity": 15,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 46,
    "name": "Hand-Carved Sheesham Wood Wall Clock",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Silent sweep wall clock featuring a floral hand-carved solid wooden frame.",
    "price": 1899.0,
    "original_price": null,
    "image": "/images/products/home-sheesham-wall-clock.jpg",
    "material": "Rosewood / Sheesham Wood",
    "dimensions": "30cm diameter",
    "care_instructions": "Wipe clean. Requires 1 AA battery.",
    "stock_quantity": 7,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 47,
    "name": "Sabai Grass Woven Basket with Lid",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Multipurpose storage canister woven by Odisha women artists using Sabai grass.",
    "price": 899.0,
    "original_price": 1123.75,
    "image": "/images/products/home-sabai-grass-basket.jpg",
    "material": "Sabai Grass & Palm Leaf",
    "dimensions": "22cm height x 20cm diameter",
    "care_instructions": "Keep dry. Wipe clean.",
    "stock_quantity": 18,
    "rating": 4.6,
    "is_customizable": false
  },
  {
    "id": 48,
    "name": "Hand-Poured Soy Candle in Terracotta Pot",
    "category_id": 4,
    "category": "Home & Living",
    "category_name": "Home & Living",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Fragrant lavender infused soy wax poured into hand-painted clay matka pot.",
    "price": 599.0,
    "original_price": null,
    "image": "/images/products/home-terracotta-soy-candle.jpg",
    "material": "Soy Wax & Terracotta",
    "dimensions": "Burn time: 35 hours",
    "care_instructions": "Trim wick to 1/4 inch before burning.",
    "stock_quantity": 22,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 49,
    "name": "Handcrafted Silver Floral Filigree Necklace",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Delicate sterling silver-tone necklace featuring floral pendant crafted with fine filigree work.",
    "price": 1299.0,
    "original_price": 1623.75,
    "image": "/images/products/jewelry-silver-filigree-necklace.jpg",
    "material": "Sterling Silver Tone",
    "dimensions": "45cm chain length",
    "care_instructions": "Store in airtight pouch.",
    "stock_quantity": 11,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 50,
    "name": "Handmade Terracotta Beaded Bracelet Set",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Set of 3 stretch bracelets made from hand-moulded hand-painted terracotta beads.",
    "price": 449.0,
    "original_price": null,
    "image": "/images/products/jewelry-terracotta-beaded-bracelet.jpg",
    "material": "Hand-moulded Terracotta",
    "dimensions": "Adjustable 16\u201320cm",
    "care_instructions": "Avoid water exposure.",
    "stock_quantity": 24,
    "rating": 4.6,
    "is_customizable": false
  },
  {
    "id": 51,
    "name": "Kundan & Meenakari Drop Earrings",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Festive statement chandelier earrings featuring reverse Meenakari enamel and Kundan stones.",
    "price": 1499.0,
    "original_price": 1873.75,
    "image": "/images/products/jewelry-kundan-meenakari-earrings.jpg",
    "material": "Brass, Kundan & Enamel",
    "dimensions": "7.5cm length x 4cm width",
    "care_instructions": "Keep away from perfumes.",
    "stock_quantity": 9,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 52,
    "name": "Oxidized Silver Tribal Choker Necklace",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Heavy German silver choker necklace embossed with traditional coin and flower medallions.",
    "price": 1699.0,
    "original_price": null,
    "image": "/images/products/jewelry-oxidized-tribal-choker.jpg",
    "material": "Oxidized German Silver",
    "dimensions": "Adjustable dori thread length",
    "care_instructions": "Wipe clean with dry cloth.",
    "stock_quantity": 14,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 53,
    "name": "Hand-Carved Wooden Statement Ring",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Boho wooden ring hand-carved from dark rosewood with brass wire inlay.",
    "price": 399.0,
    "original_price": 498.75,
    "image": "/images/products/jewelry-carved-wooden-ring.jpg",
    "material": "Rosewood & Brass",
    "dimensions": "Sizes: US 6, 7, 8, 9",
    "care_instructions": "Keep away from water.",
    "stock_quantity": 18,
    "rating": 4.5,
    "is_customizable": false
  },
  {
    "id": 54,
    "name": "Dokra Cast Brass Tribal Pendant Necklace",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Lost-wax cast brass tribal motif pendant suspended on a thick braided cotton cord.",
    "price": 899.0,
    "original_price": null,
    "image": "/images/products/jewelry-dokra-brass-pendant.jpg",
    "material": "Cast Brass & Cotton Thread",
    "dimensions": "Cord length: 55cm",
    "care_instructions": "Clean with soft cloth.",
    "stock_quantity": 16,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 55,
    "name": "Hand-Embroidered Fabric Jhumka Earrings",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Lightweight round fabric jhumkas detailed with mirrorwork and dangling ghungroo bells.",
    "price": 499.0,
    "original_price": 623.75,
    "image": "/images/products/jewelry-fabric-jhumka-earrings.jpg",
    "material": "Cotton Fabric, Mirrors & Brass",
    "dimensions": "6cm length",
    "care_instructions": "Avoid moisture.",
    "stock_quantity": 22,
    "rating": 4.7,
    "is_customizable": true
  },
  {
    "id": 56,
    "name": "Pearl & Polki Hand-Crafted Nose Ring",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Traditional bridal septum clip-on ring crafted with faux pearls and uncut glass polki.",
    "price": 599.0,
    "original_price": null,
    "image": "/images/products/jewelry-polki-nose-ring.jpg",
    "material": "Gold-plated alloy & faux pearls",
    "dimensions": "2.5cm hoop diameter",
    "care_instructions": "Store dry.",
    "stock_quantity": 15,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 57,
    "name": "Hand-Hammered Brass Stackable Bangles",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Set of 6 narrow brass bangles featuring varied hammered textures and antique finish.",
    "price": 699.0,
    "original_price": 873.75,
    "image": "/images/products/jewelry-brass-stackable-bangles.jpg",
    "material": "Solid Brass",
    "dimensions": "Sizes: 2.4, 2.6, 2.8",
    "care_instructions": "Polish with brass cleaner.",
    "stock_quantity": 20,
    "rating": 4.6,
    "is_customizable": false
  },
  {
    "id": 58,
    "name": "Real Pressed Flower Resin Pendant",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Oval glass resin pendant containing real dried wildflowers on a sterling silver chain.",
    "price": 899.0,
    "original_price": null,
    "image": "/images/products/jewelry-pressed-flower-pendant.jpg",
    "material": "Clear Resin & Real Botanical",
    "dimensions": "45cm silver chain",
    "care_instructions": "Keep out of direct sunlight.",
    "stock_quantity": 13,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 59,
    "name": "Blue Pottery Ceramic Bead Necklace",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Hand-painted blue pottery ceramic spherical beads strung with lapis blue glass beads.",
    "price": 999.0,
    "original_price": 1248.75,
    "image": "/images/products/jewelry-blue-pottery-necklace.jpg",
    "material": "Quartz Pottery Beads & Silver wire",
    "dimensions": "50cm length",
    "care_instructions": "Handle ceramic beads gently.",
    "stock_quantity": 12,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 60,
    "name": "Jaipur Meenakari Peacock Anklet Pair",
    "category_id": 5,
    "category": "Jewelry",
    "category_name": "Jewelry",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Pair of traditional silver-plated payal anklets decorated with colorful peacock enamel.",
    "price": 849.0,
    "original_price": null,
    "image": "/images/products/jewelry-meenakari-peacock-anklet.jpg",
    "material": "Silver-plated alloy & enamel",
    "dimensions": "26cm length + extension",
    "care_instructions": "Store in ziplock pouch.",
    "stock_quantity": 17,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 61,
    "name": "Hand-Carved Sheesham Wood Jewelry Box",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Solid sheesham wooden keepsake box featuring detailed floral brass wire inlay on lid.",
    "price": 1249.0,
    "original_price": 1561.25,
    "image": "/images/products/gifts-carved-wooden-jewelry-box.jpg",
    "material": "Rosewood with brass wire inlay",
    "dimensions": "20cm x 12cm x 8cm",
    "care_instructions": "Wipe with dry cloth.",
    "stock_quantity": 12,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 62,
    "name": "Blue Pottery Hand-Painted Photo Frame",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Jaipur blue pottery tabletop picture frame designed for 4x6 inch memories.",
    "price": 999.0,
    "original_price": null,
    "image": "/images/products/gifts-blue-pottery-photo-frame.jpg",
    "material": "Ceramic Quartz & Glass",
    "dimensions": "Outer: 22cm x 17cm",
    "care_instructions": "Clean glass with microfiber cloth.",
    "stock_quantity": 14,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 63,
    "name": "Moradabad Engraved Brass Pen Stand",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 5,
    "artisan_name": "Kavitha Swaminathan",
    "description": "Heavy brass cylindrical desk holder intricately hand-etched with Mughal floral vines.",
    "price": 1199.0,
    "original_price": 1498.75,
    "image": "/images/products/gifts-engraved-brass-pen-stand.jpg",
    "material": "Cast Solid Brass",
    "dimensions": "12cm height x 8cm diameter",
    "care_instructions": "Polish with brass cleaner.",
    "stock_quantity": 10,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 64,
    "name": "Handcrafted Leather Journal Deckle Paper",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Refillable leather notebook with 200 pages of handmade recycled cotton deckle edge paper.",
    "price": 899.0,
    "original_price": null,
    "image": "/images/products/gifts-leather-deckle-journal.jpg",
    "material": "Genuine Leather & Cotton Paper",
    "dimensions": "A5 size (21cm x 15cm)",
    "care_instructions": "Keep dry.",
    "stock_quantity": 18,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 65,
    "name": "Soapstone Hand-Carved Aroma Oil Burner",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Jali lattice carved soapstone essential oil burner diffuser with brass dish.",
    "price": 749.0,
    "original_price": 936.25,
    "image": "/images/products/gifts-soapstone-aroma-burner.jpg",
    "material": "Natural Soft Soapstone",
    "dimensions": "11cm height x 9cm diameter",
    "care_instructions": "Wipe dish after oil use.",
    "stock_quantity": 16,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 66,
    "name": "Bidriware Silver Inlaid Keepsake Box",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Black zinc-copper alloy trinket box embellished with intricate hand-hammered silver wire.",
    "price": 2199.0,
    "original_price": null,
    "image": "/images/products/gifts-bidriware-keepsake-box.jpg",
    "material": "Bidri Alloy & Pure Silver Inlay",
    "dimensions": "12cm x 8cm x 5cm",
    "care_instructions": "Apply coconut oil to preserve patina.",
    "stock_quantity": 6,
    "rating": 5.0,
    "is_customizable": false
  },
  {
    "id": 67,
    "name": "Madhubani Wooden Tray & Coaster Set",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 8,
    "artisan_name": "Sunita Devi",
    "description": "Serving tray paired with 4 coasters, hand-painted with Madhubani peacock art.",
    "price": 1599.0,
    "original_price": 1998.75,
    "image": "/images/products/gifts-madhubani-wooden-tray.jpg",
    "material": "Mango Wood & Protective Lacquer",
    "dimensions": "Tray: 35cm x 25cm",
    "care_instructions": "Wipe clean with damp cloth.",
    "stock_quantity": 9,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 68,
    "name": "Hand-Poured Scented Beeswax Candle Set",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Gift box of 3 pure beeswax votive candles scented with natural sandalwood and rose.",
    "price": 899.0,
    "original_price": null,
    "image": "/images/products/gifts-beeswax-candle-set.jpg",
    "material": "100% Pure Beeswax & Essential oils",
    "dimensions": "Each candle: 100g",
    "care_instructions": "Burn within sight.",
    "stock_quantity": 15,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 69,
    "name": "Pashmina Silk Embroidered Stole Gift Box",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 10,
    "artisan_name": "Tenzing Norbu",
    "description": "Luxury gift box containing a hand-embroidered silk-pashmina blend unisex stole.",
    "price": 2999.0,
    "original_price": 3748.75,
    "image": "/images/products/gifts-pashmina-stole-gift-box.jpg",
    "material": "Silk Pashmina Wool",
    "dimensions": "200cm x 70cm",
    "care_instructions": "Dry clean only.",
    "stock_quantity": 5,
    "rating": 5.0,
    "is_customizable": false
  },
  {
    "id": 70,
    "name": "Carved Walnut Wood Dry Fruit Bowl",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Hand-carved Kashmiri walnut wood bowl featuring 4 divided compartments and lid.",
    "price": 1899.0,
    "original_price": null,
    "image": "/images/products/gifts-walnut-wood-dry-fruit-bowl.jpg",
    "material": "Solid Kashmiri Walnut Wood",
    "dimensions": "25cm diameter",
    "care_instructions": "Wipe clean with dry cloth.",
    "stock_quantity": 8,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 71,
    "name": "Brass Vintage Compass in Wooden Box",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Functional nautical brass pocket compass presented in a velvet-lined carved wooden case.",
    "price": 1399.0,
    "original_price": 1748.75,
    "image": "/images/products/gifts-brass-nautical-compass.jpg",
    "material": "Solid Brass & Rosewood box",
    "dimensions": "Compass: 6cm, Box: 9cm",
    "care_instructions": "Avoid water exposure.",
    "stock_quantity": 11,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 72,
    "name": "Terracotta Diya & Spice Box Set",
    "category_id": 6,
    "category": "Gifts",
    "category_name": "Gifts",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Decorative gift hamper box with 4 hand-painted terracotta oil lamps and brass spice tin.",
    "price": 999.0,
    "original_price": null,
    "image": "/images/products/gifts-terracotta-diya-spice-box.jpg",
    "material": "Clay & Brass",
    "dimensions": "Hamper box: 25cm x 25cm",
    "care_instructions": "Handle clay diya carefully.",
    "stock_quantity": 13,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 73,
    "name": "Authentic Madhubani Tree of Life Canvas",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 8,
    "artisan_name": "Sunita Devi",
    "description": "Hand-painted folk art canvas depicting the eternal Tree of Life with birds and flora.",
    "price": 2499.0,
    "original_price": 3123.75,
    "image": "/images/products/art-madhubani-tree-of-life.jpg",
    "material": "Handmade Canvas & Acrylic/Natural Ink",
    "dimensions": "60cm x 45cm (Framed)",
    "care_instructions": "Keep out of direct sunlight. Dust lightly.",
    "stock_quantity": 8,
    "rating": 5.0,
    "is_customizable": true
  },
  {
    "id": 74,
    "name": "Warli Tribal Village Celebration Canvas",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Traditional Maharashtra Warli monochromatic painting on rustic red ochre canvas.",
    "price": 1799.0,
    "original_price": null,
    "image": "/images/products/art-warli-village-canvas.jpg",
    "material": "Rice paste pigment on cloth canvas",
    "dimensions": "50cm x 40cm (Unframed)",
    "care_instructions": "Frame under glass for protection.",
    "stock_quantity": 11,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 75,
    "name": "Odisha Pattachitra Scroll Art Jagannath",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 8,
    "artisan_name": "Sunita Devi",
    "description": "Intricate cloth scroll painting depicting Lord Jagannath painted with mineral colors.",
    "price": 2899.0,
    "original_price": 3623.75,
    "image": "/images/products/art-pattachitra-jagannath-scroll.jpg",
    "material": "Cotton canvas coated with gum & chalk",
    "dimensions": "75cm x 30cm",
    "care_instructions": "Keep dry.",
    "stock_quantity": 6,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 76,
    "name": "Tanjore Gold Leaf Painting of Lakshmi",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Rich South Indian Tanjore artwork embellished with 22k gold foil and semi-precious gems.",
    "price": 4999.0,
    "original_price": null,
    "image": "/images/products/art-tanjore-gold-leaf-lakshmi.jpg",
    "material": "Teakwood board, Gold foil & Glass beads",
    "dimensions": "40cm x 30cm (Framed)",
    "care_instructions": "Dust glass frame carefully.",
    "stock_quantity": 4,
    "rating": 5.0,
    "is_customizable": true
  },
  {
    "id": 77,
    "name": "Hand-Carved Teakwood Relief Wall Panel",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "3D wooden wall relief carved with lotus flowers and peacock pairs from a single wood block.",
    "price": 3499.0,
    "original_price": 4373.75,
    "image": "/images/products/art-teakwood-relief-wall-panel.jpg",
    "material": "Reclaimed Teakwood",
    "dimensions": "60cm x 30cm x 4cm",
    "care_instructions": "Apply wood wax polish annually.",
    "stock_quantity": 5,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 78,
    "name": "Rajasthani Pichwai Lotus Canvas Painting",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Nathdwara style Pichwai wall canvas featuring pink lotus blooms and holy cows.",
    "price": 2299.0,
    "original_price": null,
    "image": "/images/products/art-pichwai-lotus-canvas.jpg",
    "material": "Cotton Canvas & Watercolors",
    "dimensions": "60cm x 60cm",
    "care_instructions": "Keep away from moisture.",
    "stock_quantity": 9,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 79,
    "name": "Gond Art Wildlife Canvas Peacock & Deer",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Madhya Pradesh Gond tribal painting filled with intricate line and dot patterns.",
    "price": 1999.0,
    "original_price": 2498.75,
    "image": "/images/products/art-gond-wildlife-canvas.jpg",
    "material": "Canvas & Acrylic colors",
    "dimensions": "50cm x 40cm",
    "care_instructions": "Dust gently with dry cloth.",
    "stock_quantity": 10,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 80,
    "name": "Phad Folk Painting Royal Procession",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 8,
    "artisan_name": "Sunita Devi",
    "description": "Rajasthan Phad scroll painting depicting a royal king's procession on horses and elephants.",
    "price": 2699.0,
    "original_price": null,
    "image": "/images/products/art-phad-royal-procession.jpg",
    "material": "Handspun Khadi Canvas",
    "dimensions": "90cm x 35cm",
    "care_instructions": "Store unrolled or framed.",
    "stock_quantity": 7,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 81,
    "name": "Terracotta Hand-Sculpted Wall Mask",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 1,
    "artisan_name": "Rajesh Kumar",
    "description": "Tribal face mask hand-moulded from red clay and hand-painted with earthen pigments.",
    "price": 1199.0,
    "original_price": 1498.75,
    "image": "/images/products/art-terracotta-wall-mask.jpg",
    "material": "Baked Terracotta Clay",
    "dimensions": "30cm height x 18cm width",
    "care_instructions": "Mount securely on wall hook.",
    "stock_quantity": 12,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 82,
    "name": "Cheriyal Scroll Miniature Painting",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Telangana folk art painting on treated cloth portraying village stories.",
    "price": 1899.0,
    "original_price": null,
    "image": "/images/products/art-cheriyal-miniature-scroll.jpg",
    "material": "Treated Khadi cloth & Natural dyes",
    "dimensions": "45cm x 30cm",
    "care_instructions": "Keep away from direct sunlight.",
    "stock_quantity": 8,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 83,
    "name": "Kalamkari Tree of Knowledge Wall Hanging",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Hand-painted cotton wall scroll created using bamboo pen and natural vegetable dyes.",
    "price": 1699.0,
    "original_price": 2123.75,
    "image": "/images/products/art-kalamkari-wall-hanging.jpg",
    "material": "100% Cotton & Natural Dyes",
    "dimensions": "100cm x 65cm",
    "care_instructions": "Dry clean only.",
    "stock_quantity": 14,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 84,
    "name": "Kalighat Style Folk Art Canvas Frame",
    "category_id": 7,
    "category": "Art & Crafts",
    "category_name": "Art & Crafts",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Bold line watercolor painting inspired by 19th-century Bengal Kalighat temple art.",
    "price": 1499.0,
    "original_price": null,
    "image": "/images/products/art-kalighat-folk-art-canvas.jpg",
    "material": "Handmade Paper & Watercolors",
    "dimensions": "40cm x 30cm (Framed)",
    "care_instructions": "Handle glass frame carefully.",
    "stock_quantity": 13,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 85,
    "name": "Shantiniketan Embossed Leather Tote Bag",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 3,
    "artisan_name": "Arjun Somvanshi",
    "description": "Spacious leather shoulder tote embossed with traditional West Bengal batik floral art.",
    "price": 2499.0,
    "original_price": 3123.75,
    "image": "/images/products/bags-shantiniketan-leather-tote.jpg",
    "material": "Vegetable-tanned Leather",
    "dimensions": "38cm x 30cm x 12cm",
    "care_instructions": "Condition with leather cream.",
    "stock_quantity": 10,
    "rating": 4.9,
    "is_customizable": true
  },
  {
    "id": 86,
    "name": "Hand-Embroidered Kutch Zipper Clutch",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "Ethnic pouch clutch embellished with dense colorful embroidery and mirrorwork.",
    "price": 899.0,
    "original_price": null,
    "image": "/images/products/bags-kutch-zipper-clutch.jpg",
    "material": "Cotton Fabric & Glass Mirrors",
    "dimensions": "24cm x 14cm",
    "care_instructions": "Dry clean only.",
    "stock_quantity": 18,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 87,
    "name": "Natural Jute & Leather Messenger Bag",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Sturdy laptop messenger bag crafted from eco jute canvas with genuine leather trim.",
    "price": 1899.0,
    "original_price": 2373.75,
    "image": "/images/products/bags-jute-leather-messenger.jpg",
    "material": "Eco Jute & Full-grain Leather",
    "dimensions": "40cm x 30cm x 8cm",
    "care_instructions": "Spot clean canvas.",
    "stock_quantity": 12,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 88,
    "name": "Banjara Boho Tribal Patchwork Sling",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "One-of-a-kind vintage cotton patchwork crossbody bag with coin tassles.",
    "price": 1299.0,
    "original_price": null,
    "image": "/images/products/bags-banjara-patchwork-sling.jpg",
    "material": "Vintage Cotton & Brass Coins",
    "dimensions": "28cm x 22cm, Strap 120cm",
    "care_instructions": "Hand wash cold gently.",
    "stock_quantity": 14,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 89,
    "name": "Kalamkari Hand-Block Canvas Tote Bag",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 9,
    "artisan_name": "Lalita Rathore",
    "description": "Eco-friendly reusable shopping tote bag featuring hand-printed Kalamkari bootis.",
    "price": 799.0,
    "original_price": 998.75,
    "image": "/images/products/bags-kalamkari-canvas-tote.jpg",
    "material": "100% Heavy Cotton Canvas",
    "dimensions": "40cm x 35cm",
    "care_instructions": "Machine wash cold inside out.",
    "stock_quantity": 22,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 90,
    "name": "Handcrafted Bamboo Rigid Handbag",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Structured box handbag hand-woven from natural bamboo splits with wooden handle.",
    "price": 1699.0,
    "original_price": null,
    "image": "/images/products/bags-bamboo-rigid-handbag.jpg",
    "material": "Natural Bamboo & Wood",
    "dimensions": "24cm x 18cm x 10cm",
    "care_instructions": "Keep dry.",
    "stock_quantity": 9,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 91,
    "name": "Hand-Woven Macrame Boho Crossbody Sling",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Bohemian macrame camera bag knotted from natural cream cotton yarn.",
    "price": 1199.0,
    "original_price": 1498.75,
    "image": "/images/products/bags-macrame-crossbody-sling.jpg",
    "material": "100% Natural Cotton Cord",
    "dimensions": "22cm x 18cm",
    "care_instructions": "Hand wash cold water.",
    "stock_quantity": 16,
    "rating": 4.8,
    "is_customizable": true
  },
  {
    "id": 92,
    "name": "Banarasi Brocade Potli Evening Bag",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Festive drawstring handbag made of gold Banarasi brocade fabric with pearl handle.",
    "price": 999.0,
    "original_price": null,
    "image": "/images/products/bags-banarasi-brocade-potli.jpg",
    "material": "Zari Brocade & Faux Pearls",
    "dimensions": "20cm x 18cm",
    "care_instructions": "Spot clean only.",
    "stock_quantity": 15,
    "rating": 4.8,
    "is_customizable": false
  },
  {
    "id": 93,
    "name": "Hand-Painted Madhubani Leather Wallet",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 4,
    "artisan_name": "Ananya Bose",
    "description": "Slim bi-fold men's/unisex leather wallet adorned with hand-painted fish motifs.",
    "price": 999.0,
    "original_price": 1248.75,
    "image": "/images/products/bags-madhubani-leather-wallet.jpg",
    "material": "Genuine Goat Leather",
    "dimensions": "11cm x 9cm closed",
    "care_instructions": "Do not rub painted area.",
    "stock_quantity": 17,
    "rating": 4.9,
    "is_customizable": false
  },
  {
    "id": 94,
    "name": "Palm Leaf Woven Market Basket Tote",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 2,
    "artisan_name": "Meenakshi Sundaram",
    "description": "Structured eco-friendly shopping basket woven from sturdy dried palm leaves.",
    "price": 849.0,
    "original_price": null,
    "image": "/images/products/bags-palm-leaf-woven-basket.jpg",
    "material": "Dried Natural Palm Leaves",
    "dimensions": "35cm x 28cm x 15cm",
    "care_instructions": "Wipe clean with damp cloth.",
    "stock_quantity": 20,
    "rating": 4.6,
    "is_customizable": true
  },
  {
    "id": 95,
    "name": "Kantha Stitch Denim Travel Pouch",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Upcycled denim toiletries pouch decorated with running Kantha embroidery.",
    "price": 649.0,
    "original_price": 811.25,
    "image": "/images/products/bags-kantha-denim-travel-pouch.jpg",
    "material": "Upcycled Denim & Cotton Thread",
    "dimensions": "22cm x 14cm x 8cm",
    "care_instructions": "Machine wash cold.",
    "stock_quantity": 24,
    "rating": 4.7,
    "is_customizable": false
  },
  {
    "id": 96,
    "name": "Raw Silk Envelope Clutch Zardozi",
    "category_id": 8,
    "category": "Bags & Accessories",
    "category_name": "Bags & Accessories",
    "artisan_id": 7,
    "artisan_name": "Fatima Sheikh",
    "description": "Sophisticated evening envelope clutch bag featuring hand-stitched gold wire Zardozi.",
    "price": 1499.0,
    "original_price": null,
    "image": "/images/products/bags-raw-silk-zardozi-clutch.jpg",
    "material": "Pure Raw Silk & Metallic Wire",
    "dimensions": "26cm x 15cm",
    "care_instructions": "Dry clean only.",
    "stock_quantity": 11,
    "rating": 4.9,
    "is_customizable": false
  }
];
