-- ============================================================
-- CRAFTORA: DATABASE SEED DATA (12 Products per Category = 96 Sample Products)
-- ============================================================

USE craftora_db;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE reviews;
TRUNCATE TABLE order_items;
TRUNCATE TABLE orders;
TRUNCATE TABLE cart_items;
TRUNCATE TABLE cart;
TRUNCATE TABLE wishlist;
TRUNCATE TABLE product_images;
TRUNCATE TABLE products;
TRUNCATE TABLE artisans;
TRUNCATE TABLE categories;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

-- 1. USERS
INSERT INTO users (id, name, email, password_hash, avatar, role) VALUES
(1, 'Craftora Admin',  'admin@craftora.com',   'scrypt:32768:8:1$CkAufU7snPuBtqbJ$5d4250eeb6bfb0f6e9a437cd0b86ba41b54b1d661abd08972066d834a695a560ea5f93c849a82ac6202f4901785df3673c099fdfccaf41bdca055d9ff70b8571', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80', 'ADMIN'),
(2, 'Ananya Sharma',   'ananya@example.com',   'scrypt:32768:8:1$CkAufU7snPuBtqbJ$5d4250eeb6bfb0f6e9a437cd0b86ba41b54b1d661abd08972066d834a695a560ea5f93c849a82ac6202f4901785df3673c099fdfccaf41bdca055d9ff70b8571', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80', 'USER'),
(3, 'Rohan Verma',     'rohan@example.com',    'scrypt:32768:8:1$CkAufU7snPuBtqbJ$5d4250eeb6bfb0f6e9a437cd0b86ba41b54b1d661abd08972066d834a695a560ea5f93c849a82ac6202f4901785df3673c099fdfccaf41bdca055d9ff70b8571', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80', 'USER');

-- 2. CATEGORIES
INSERT INTO categories (id, name, description, image) VALUES
(1, 'Men',                'Handmade kurtas, wallets, bracelets, belts & accessories for men.',          '/images/products/men-handloom-kurta.jpg'),
(2, 'Women',              'Sarees, dupattas, jewellery, handbags & accessories for women.',             '/images/products/women-kanjeevaram-saree.jpg'),
(3, 'Kids',               'Handmade wooden toys, soft toys, puzzles & personalised baby gifts.',       '/images/products/kids-channapatna-stacking-rings.jpg'),
(4, 'Home & Living',      'Pottery, wall art, candles, macrame, lamps & handmade table decor.',        '/images/products/home-blue-pottery-vase.jpg'),
(5, 'Jewelry',            'Necklaces, earrings, bracelets, rings, silver & personalised jewellery.',   '/images/products/jewelry-silver-filigree-necklace.jpg'),
(6, 'Gifts',              'Birthday, wedding, anniversary & personalised gifts for every occasion.',    '/images/products/gifts-carved-wooden-jewelry-box.jpg'),
(7, 'Art & Crafts',       'Madhubani, Pithora, resin art, woodcraft & traditional Indian art.',        '/images/products/art-madhubani-tree-of-life.jpg'),
(8, 'Bags & Accessories', 'Tote bags, handbags, sling bags, wallets, pouches & keychains.',            '/images/products/bags-shantiniketan-leather-tote.jpg');

-- 3. ARTISANS
INSERT INTO artisans (id, name, bio, specialty, location, image, experience, rating) VALUES
(1,  'Rajesh Kumar',       'Preserving 3rd-generation blue pottery traditions with sustainable natural glazes and custom monogram engravings.', 'Master Potter & Ceramicist',      'Jaipur, Rajasthan',          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80', '18+ years', 4.9),
(2,  'Meenakshi Sundaram', 'Weaving hand-spun organic cotton and natural vegetable dye tapestries using authentic wooden pit looms.',          'Handloom & Textile Weaver',       'Madurai, Tamil Nadu',         'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80', '12+ years', 4.8),
(3,  'Arjun Somvanshi',    'Hand-carving reclaimed rosewood and teak into timeless keepsake boxes and architectural accents.',                  'Rosewood & Brass Craftsman',      'Saharanpur, Uttar Pradesh',   'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80', '15+ years', 5.0),
(4,  'Ananya Bose',        'Blending Madhubani and Warli folk art with contemporary resin art — each piece is an original creation.',          'Folk Painter & Resin Artist',     'Kolkata, West Bengal',        'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80', '8+ years',  4.9),
(5,  'Kavitha Swaminathan', 'Creating contemporary handcrafted jewellery blending tribal traditions with modern aesthetics using recycled metals.', 'Jewellery & Metalwork Artist',  'Chennai, Tamil Nadu',         'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80', '10+ years', 4.8),
(6,  'Balram Patra',       'A 4th-generation Channapatna craftsman preserving the art of turning eco-toys using natural lacquer.',             'Channapatna Lacquerwood Artist',  'Channapatna, Karnataka',      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80', '20+ years', 4.9),
(7,  'Fatima Sheikh',      'Creating heritage Zardozi embroidery using metallic gold and silver threads on velvet and silk fabrics.',          'Zardozi Thread Embroiderer',      'Lucknow, Uttar Pradesh',      'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=300&q=80', '11+ years', 4.9),
(8,  'Sunita Devi',        'National award-winning Mithila artist painting stories of folklore and nature onto handmade cotton parchment.',    'Madhubani Master Painter',        'Madhubani, Bihar',            'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80', '20+ years', 5.0),
(9,  'Lalita Rathore',     'Practicing traditional Dabu mud-resist and Bagru block printing with natural indigo vats.',                        'Block Print Artisan',             'Bagru, Rajasthan',            'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=300&q=80', '13+ years', 4.8),
(10, 'Tenzing Norbu',      'Hand-knotting pure sheep wool rugs and Himalayan meditation prayer accessories for 17 years.',                     'Himalayan Wool Weaver',           'Dharamshala, Himachal Pradesh','https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80', '17+ years', 4.9);

-- 4. PRODUCTS (96 Total: 12 per category)
INSERT INTO products (id, artisan_id, category_id, name, description, price, image, material, dimensions, care_instructions, stock_quantity, rating) VALUES
(1, 9, 1, 'Handloom Cotton Kurta with Mirror Work', 'Classic mens kurta handwoven from premium cotton with hand-stitched mirror work detailing on collar and cuffs.', 1199.00, '/images/products/men-handloom-kurta.jpg', 'Handloom cotton with mirror embroidery', 'Sizes: S, M, L, XL, XXL', 'Gentle machine wash cold. Iron on reverse.', 12, 4.7),
(2, 3, 1, 'Shantiniketan Embossed Leather Folio', 'Handcrafted Shantiniketan embossed leather folio featuring traditional floral motifs, crafted using vegetable dyes.', 1249.00, '/images/products/men-leather-folio.jpg', 'Vegetable-tanned goat leather', '32cm x 24cm', 'Condition with leather wax every 6 months.', 9, 4.9),
(3, 7, 1, 'Hand-Embroidered Kashmiri Aari Waistcoat', 'Traditional handcrafted Kashmiri men''s waistcoat featuring intricate floral Aari thread embroidery on raw silk.', 2499.00, '/images/products/men-kashmiri-waistcoat.jpg', 'Pure raw silk with wool Aari embroidery', 'Sizes: S, M, L, XL', 'Dry clean only. Store in cotton bag.', 8, 4.8),
(4, 5, 1, 'Handcrafted Leather & Brass Bracelet', 'Braided genuine leather bracelet with hand-hammered brass medallion stamped with traditional motifs.', 599.00, '/images/products/men-leather-brass-bracelet.jpg', 'Vegetable-tanned leather & brass', 'Adjustable 18–22cm', 'Wipe clean with dry cloth.', 14, 4.7),
(5, 2, 1, 'Hand-Woven Khadi Stole for Men', 'Soft hand-spun khadi cotton stole with natural vegetable-dyed stripe border.', 750.00, '/images/products/men-khadi-stole.jpg', 'Pure hand-spun khadi cotton', '200cm x 55cm', 'Gentle hand wash cold.', 10, 4.5),
(6, 9, 1, 'Rajasthani Mojari Hand-Stitched Leather Shoes', 'Authentic leather mojari footwear hand-stitched with colorful thread and traditional motifs.', 1499.00, '/images/products/men-rajasthani-mojari.jpg', 'Genuine camel leather', 'Sizes: UK 7 to 11', 'Keep away from water. Use leather polish.', 15, 4.8),
(7, 9, 1, 'Organic Indigo Dabu Block Print Shirt', 'Pure cotton men''s casual shirt dyed in natural indigo vats using age-old Dabu mud-resist block technique.', 1350.00, '/images/products/men-dabu-block-shirt.jpg', '100% organic cotton', 'Sizes: S, M, L, XL', 'Wash separately in cold water with mild detergent.', 18, 4.6),
(8, 3, 1, 'Hand-Carved Teakwood Cufflinks & Box Set', 'Square teakwood cufflinks brass-inlaid with geometric patterns, stored in a hand-carved mini chest.', 899.00, '/images/products/men-teakwood-cufflinks.jpg', 'Reclaimed teakwood & brass', 'Cufflinks: 1.5cm, Box: 8cm x 5cm', 'Wipe wood with dry microfiber cloth.', 11, 4.9),
(9, 2, 1, 'Chanderi Silk Men''s Dupatta with Zari Border', 'Elegant lightweight Chanderi silk stole featuring woven gold zari border for festive occasions.', 1699.00, '/images/products/men-chanderi-dupatta.jpg', 'Chanderi silk-cotton blend with gold zari', '230cm x 60cm', 'Dry clean recommended.', 7, 4.7),
(10, 5, 1, 'Handcrafted Brass Buckle Leather Belt', 'Full-grain leather belt paired with a hand-cast solid brass buckle stamped with mandala art.', 1099.00, '/images/products/men-brass-leather-belt.jpg', 'Full-grain cowhide leather & brass', 'Length: 32 - 42 inches', 'Condition leather periodically.', 20, 4.8),
(11, 10, 1, 'Pashmina Wool Muffler with Sozni Stitch', 'Warm Himalayan sheep wool muffler delicately decorated with hand-embroidered Sozni needlework.', 2899.00, '/images/products/men-pashmina-muffler.jpg', '100% Himalayan Pashmina Wool', '180cm x 35cm', 'Dry clean only. Store with cedar balls.', 6, 5.0),
(12, 1, 1, 'Kolhapuri Hand-Carved Leather Sandals', 'Traditional Kolhapuri leather chappal with braided strap detailing and sturdy hand-stitched soles.', 1299.00, '/images/products/men-kolhapuri-sandals.jpg', 'Tanned buffalo leather', 'Sizes: UK 6 to 11', 'Apply mustard oil occasionally for softness.', 13, 4.6),
(13, 2, 2, 'Pure Kanjeevaram Silk Saree with Zari Motif', 'Lustrous mulberry silk saree handwoven in Kanchipuram with rich gold zari peacock border.', 4999.00, '/images/products/women-kanjeevaram-saree.jpg', 'Pure Mulberry Silk & Gold Zari', 'Saree: 5.5m + 0.8m Blouse', 'Dry clean only. Store in muslin cloth.', 6, 4.9),
(14, 9, 2, 'Hand-Block Printed Chanderi Cotton Dupatta', 'Breathable lightweight Chanderi fabric adorned with Bagru block floral prints and zari trim.', 899.00, '/images/products/women-chanderi-dupatta.jpg', 'Chanderi silk-cotton', '2.4m x 0.9m', 'Gentle hand wash in cold water.', 18, 4.7),
(15, 7, 2, 'Chikankari Embroidered Georgette Kurti', 'Ethereal Lucknowi Chikankari embroidered kurti with intricate Shadow and Bakhiya stitches.', 1899.00, '/images/products/women-chikankari-kurti.jpg', 'Faux georgette with cotton thread', 'Sizes: XS to XXL', 'Hand wash cold or dry clean.', 12, 4.8),
(16, 7, 2, 'Phulkari Hand-Embroidered Velvet Shawl', 'Vibrant Punjabi Phulkari floral thread embroidery on rich maroon velvet base fabric.', 2799.00, '/images/products/women-phulkari-shawl.jpg', 'Velvet fabric with rayon thread', '2.2m x 1.0m', 'Dry clean only.', 9, 4.9),
(17, 9, 2, 'Bandhani Tie & Dye Mulberry Silk Dupatta', 'Traditional Rajasthani tie-and-dye dupatta featuring thousands of tiny hand-tied dots.', 1599.00, '/images/products/women-bandhani-dupatta.jpg', '100% Pure Mulberry Silk', '2.5m x 1.0m', 'Dry clean only. Preserve roll crush.', 11, 4.8),
(18, 7, 2, 'Banarasi Brocade Potli Bag & Saree Belt', 'Coordinated festive set featuring a woven zari potli handbag and matching embroidered waist belt.', 1299.00, '/images/products/women-banarasi-potli-belt.jpg', 'Banarasi silk brocade & metallic zari', 'Potli: 20cm x 18cm, Belt: Adjustable', 'Spot clean only.', 14, 4.7),
(19, 4, 2, 'Kalamkari Hand-Painted Cotton Saree', 'Srikalahasti style hand-painted saree depicting mythological lore painted with natural dyes.', 3499.00, '/images/products/women-kalamkari-saree.jpg', '100% Handloom Cotton', 'Saree: 5.5m + Blouse', 'Dry clean recommended.', 5, 5.0),
(20, 2, 2, 'Sambalpuri Ikat Weave Cotton Kurta Set', 'Authentic Odisha double-ikat weave cotton kurti paired with matching plain palazzo pants.', 2199.00, '/images/products/women-ikat-kurta-set.jpg', 'Pure Handloom Ikat Cotton', 'Sizes: S, M, L, XL', 'Gentle wash cold separately.', 10, 4.8),
(21, 7, 2, 'Hand-Embroidered Zardozi Velvet Jacket', 'Royal festive layering jacket handcrafted with heavy gold zari, pearls, and metallic wire threadwork.', 3899.00, '/images/products/women-zardozi-jacket.jpg', 'Rich Silk Velvet & Zardozi Wire', 'Sizes: S, M, L', 'Dry clean only.', 4, 4.9),
(22, 2, 2, 'Maheshwari Handloom Silk Cotton Saree', 'Classic Maheshwari saree featuring reversible zari border and traditional check pattern weave.', 2699.00, '/images/products/women-maheshwari-saree.jpg', 'Silk-Cotton Blend', 'Saree: 5.5m + Blouse', 'Dry clean for first wash.', 8, 4.8),
(23, 2, 2, 'Pochampally Ikat Weave Cotton Dupatta', 'Geometric ikat pattern handwoven by Telangana master weavers using resist-dyed cotton yarn.', 1199.00, '/images/products/women-pochampally-dupatta.jpg', '100% Mercerized Cotton', '2.4m x 0.9m', 'Hand wash with mild liquid detergent.', 15, 4.7),
(24, 2, 2, 'Jamdani Hand-Woven Muslin Cotton Saree', 'Featherlight Bengal Jamdani saree with extra-weft motif weaving that floats on sheer fabric.', 3299.00, '/images/products/women-jamdani-saree.jpg', 'Fine Muslin Cotton', 'Saree: 5.5m + Blouse', 'Hand wash with care or dry clean.', 7, 4.9),
(25, 6, 3, 'Channapatna Lacquerwood Stacking Rings', 'Classic eco-friendly wooden stacking tower painted with non-toxic vegetable dyes.', 599.00, '/images/products/kids-channapatna-stacking-rings.jpg', 'Wrightia tinctoria wood & organic lacquer', '18cm height', 'Wipe clean with dry cloth.', 20, 4.9),
(26, 2, 3, 'Handmade Organic Cotton Elephant Soft Toy', 'Plush elephant stuffed toy hand-stitched from GOTS certified organic cotton fabric.', 699.00, '/images/products/kids-cotton-elephant-toy.jpg', 'Organic Cotton & Recycled Fiberfill', '22cm length', 'Machine washable gentle cycle.', 15, 4.8),
(27, 8, 3, 'Hand-Painted Madhubani Wooden Blocks', 'Set of 12 solid wooden building blocks hand-painted with colorful animal figures.', 899.00, '/images/products/kids-madhubani-wooden-blocks.jpg', 'Natural Mango wood & child-safe paint', 'Each block: 4cm cube', 'Wipe with soft cloth.', 12, 4.9),
(28, 6, 3, 'Kondapalli Wooden Dancing Doll Toy', 'Traditional Andhra bobblehead dancing lady toy handcrafted from light softwood.', 749.00, '/images/products/kids-kondapalli-dancing-doll.jpg', 'Tella Poniki wood & natural colors', '25cm height', 'Handle with care.', 14, 4.7),
(29, 10, 3, 'Hand-Knitted Wool Baby Booties & Beanie', 'Ultra-soft baby winter booties and matching bear-ear beanie hand-knitted from merino wool.', 649.00, '/images/products/kids-wool-baby-booties.jpg', '100% Soft Merino Wool', '0 - 12 Months size', 'Hand wash cold gently.', 18, 4.9),
(30, 6, 3, 'Channapatna Wooden Push Toy Car', 'Smooth rolling toy car turned on traditional wooden lathe without sharp edges.', 499.00, '/images/products/kids-channapatna-toy-car.jpg', 'Lacquerwood', '14cm x 8cm', 'Wipe with dry cloth.', 22, 4.8),
(31, 6, 3, 'Eco Bamboo Xylophone & Mallet for Toddlers', 'Handcrafted bamboo musical xylophone tuned to produces soft melodic tones.', 999.00, '/images/products/kids-bamboo-xylophone.jpg', 'Natural Bamboo & Teak mallets', '30cm x 15cm', 'Keep dry.', 11, 4.7),
(32, 6, 3, 'Kinnal Handcrafted Wooden Animal Set', 'Set of 5 hand-carved wooden jungle animal figures decorated with natural pigments.', 1199.00, '/images/products/kids-kinnal-wooden-animals.jpg', 'Kinnal softwood & natural paste', 'Average size: 10cm', 'Wipe clean gently.', 9, 4.9),
(33, 2, 3, 'Hand-Stitched Patchwork Baby Quilt', 'Reversible soft cotton baby blanket stuffed with pure cotton battings.', 1299.00, '/images/products/kids-patchwork-baby-quilt.jpg', '100% Cotton fabric & fill', '110cm x 90cm', 'Machine wash cold gentle.', 10, 4.8),
(34, 1, 3, 'Natural Clay Bhatukali Mini Cooking Set', 'Traditional 10-piece miniature kitchen play set hand-moulded from red terracotta clay.', 549.00, '/images/products/kids-terracotta-mini-cookware.jpg', 'Terracotta Clay', 'Miniature cookware pieces', 'Do not drop on hard surfaces.', 16, 4.6),
(35, 9, 3, 'Soft Handloom Cotton Baby Swaddle Cloth', 'Set of 2 breathable pre-washed cotton muslin swaddle wraps with block prints.', 799.00, '/images/products/kids-cotton-swaddle-cloth.jpg', '100% Muslin Cotton', '100cm x 100cm', 'Machine wash warm.', 25, 4.9),
(36, 6, 3, 'Channapatna Wooden Bowling Pins Set', '6 vibrant colorful wooden pins and 2 balls for fun indoor bowling play.', 1099.00, '/images/products/kids-channapatna-bowling-pins.jpg', 'Seasoned Wood & Lacquer', 'Pin height: 16cm', 'Wipe with clean cloth.', 13, 4.8),
(37, 1, 4, 'Hand-Painted Blue Pottery Ceramic Vase', 'Jaipur blue pottery necked flower vase featuring hand-painted cobalt floral arabesques.', 1499.00, '/images/products/home-blue-pottery-vase.jpg', 'Quartz powder, glass & natural oxide', '24cm height x 12cm diameter', 'Wipe clean with soft damp cloth.', 10, 4.9),
(38, 2, 4, 'Macrame Hand-Woven Wall Hanging', 'Bohemian geometric wall tapestry knotted from natural unbleached cotton cord.', 1299.00, '/images/products/home-macrame-wall-hanging.jpg', '100% Natural Cotton Rope & Driftwood', '65cm length x 40cm width', 'Gentle shake to dust. Do not wash.', 14, 4.8),
(39, 3, 4, 'Hand-Carved Teakwood Coaster Set', 'Set of 6 square wooden drink coasters brass-inlaid with traditional lotus motif.', 799.00, '/images/products/home-teakwood-coaster-set.jpg', 'Teakwood with brass wire inlay', '10cm x 10cm each', 'Wipe dry after spills. Oil wood occasionally.', 20, 4.9),
(40, 1, 4, 'Terracotta Hand-Moulded Table Lamp', 'Earthen terracotta lamp base accompanied by a hand-block printed cotton drum shade.', 2199.00, '/images/products/home-terracotta-table-lamp.jpg', 'Natural Baked Clay & Cotton Shade', 'Total Height: 45cm', 'Dust shade with soft brush. B22 bulb required.', 8, 4.8),
(41, 5, 4, 'Brass Dhokra Tribal Candle Holder', 'Lost-wax cast brass candle holder depicting a pair of tribal musicians.', 1199.00, '/images/products/home-dhokra-candle-holder.jpg', 'Cast Brass', '18cm x 12cm', 'Clean with brass polish.', 12, 4.7),
(42, 9, 4, 'Hand-Block Printed Cotton Table Runner', '100% cotton table runner printed with traditional Mughal floral bootis and tassels.', 899.00, '/images/products/home-block-print-table-runner.jpg', 'Pure Heavy Cotton Canvas', '180cm x 35cm', 'Cold machine wash. Iron on reverse.', 16, 4.8),
(43, 3, 4, 'Bidriware Silver Inlaid Marble Coasters', 'Set of 4 black Bidri alloy coasters with fine silver floral wire inlay.', 1699.00, '/images/products/home-bidriware-marble-coasters.jpg', 'Zinc Alloy & Pure Silver Inlay', '9cm diameter', 'Apply coconut oil to maintain shine.', 9, 5.0),
(44, 2, 4, 'Handloom Jute & Cotton Braided Floor Rug', 'Reversible eco-friendly area floor mat hand-braided from natural jute and cotton yarn.', 1999.00, '/images/products/home-jute-braided-rug.jpg', '70% Jute, 30% Cotton', '120cm x 80cm', 'Vacuum regularly. Spot clean with damp cloth.', 11, 4.7),
(45, 8, 4, 'Madhubani Hand-Painted Ceramic Tea Cups', 'Set of 6 ceramic kulhad style tea cups decorated with colorful Madhubani fish motifs.', 1199.00, '/images/products/home-madhubani-ceramic-cups.jpg', 'Stoneware Ceramic', 'Capacity: 180ml each', 'Microwave & Dishwasher safe.', 15, 4.9),
(46, 3, 4, 'Hand-Carved Sheesham Wood Wall Clock', 'Silent sweep wall clock featuring a floral hand-carved solid wooden frame.', 1899.00, '/images/products/home-sheesham-wall-clock.jpg', 'Rosewood / Sheesham Wood', '30cm diameter', 'Wipe clean. Requires 1 AA battery.', 7, 4.8),
(47, 2, 4, 'Sabai Grass Woven Basket with Lid', 'Multipurpose storage canister woven by Odisha women artists using Sabai grass.', 899.00, '/images/products/home-sabai-grass-basket.jpg', 'Sabai Grass & Palm Leaf', '22cm height x 20cm diameter', 'Keep dry. Wipe clean.', 18, 4.6),
(48, 1, 4, 'Hand-Poured Soy Candle in Terracotta Pot', 'Fragrant lavender infused soy wax poured into hand-painted clay matka pot.', 599.00, '/images/products/home-terracotta-soy-candle.jpg', 'Soy Wax & Terracotta', 'Burn time: 35 hours', 'Trim wick to 1/4 inch before burning.', 22, 4.9),
(49, 5, 5, 'Handcrafted Silver Floral Filigree Necklace', 'Delicate sterling silver-tone necklace featuring floral pendant crafted with fine filigree work.', 1299.00, '/images/products/jewelry-silver-filigree-necklace.jpg', 'Sterling Silver Tone', '45cm chain length', 'Store in airtight pouch.', 11, 4.8),
(50, 5, 5, 'Handmade Terracotta Beaded Bracelet Set', 'Set of 3 stretch bracelets made from hand-moulded hand-painted terracotta beads.', 449.00, '/images/products/jewelry-terracotta-beaded-bracelet.jpg', 'Hand-moulded Terracotta', 'Adjustable 16–20cm', 'Avoid water exposure.', 24, 4.6),
(51, 5, 5, 'Kundan & Meenakari Drop Earrings', 'Festive statement chandelier earrings featuring reverse Meenakari enamel and Kundan stones.', 1499.00, '/images/products/jewelry-kundan-meenakari-earrings.jpg', 'Brass, Kundan & Enamel', '7.5cm length x 4cm width', 'Keep away from perfumes.', 9, 4.9),
(52, 5, 5, 'Oxidized Silver Tribal Choker Necklace', 'Heavy German silver choker necklace embossed with traditional coin and flower medallions.', 1699.00, '/images/products/jewelry-oxidized-tribal-choker.jpg', 'Oxidized German Silver', 'Adjustable dori thread length', 'Wipe clean with dry cloth.', 14, 4.8),
(53, 3, 5, 'Hand-Carved Wooden Statement Ring', 'Boho wooden ring hand-carved from dark rosewood with brass wire inlay.', 399.00, '/images/products/jewelry-carved-wooden-ring.jpg', 'Rosewood & Brass', 'Sizes: US 6, 7, 8, 9', 'Keep away from water.', 18, 4.5),
(54, 5, 5, 'Dokra Cast Brass Tribal Pendant Necklace', 'Lost-wax cast brass tribal motif pendant suspended on a thick braided cotton cord.', 899.00, '/images/products/jewelry-dokra-brass-pendant.jpg', 'Cast Brass & Cotton Thread', 'Cord length: 55cm', 'Clean with soft cloth.', 16, 4.7),
(55, 7, 5, 'Hand-Embroidered Fabric Jhumka Earrings', 'Lightweight round fabric jhumkas detailed with mirrorwork and dangling ghungroo bells.', 499.00, '/images/products/jewelry-fabric-jhumka-earrings.jpg', 'Cotton Fabric, Mirrors & Brass', '6cm length', 'Avoid moisture.', 22, 4.7),
(56, 5, 5, 'Pearl & Polki Hand-Crafted Nose Ring', 'Traditional bridal septum clip-on ring crafted with faux pearls and uncut glass polki.', 599.00, '/images/products/jewelry-polki-nose-ring.jpg', 'Gold-plated alloy & faux pearls', '2.5cm hoop diameter', 'Store dry.', 15, 4.8),
(57, 5, 5, 'Hand-Hammered Brass Stackable Bangles', 'Set of 6 narrow brass bangles featuring varied hammered textures and antique finish.', 699.00, '/images/products/jewelry-brass-stackable-bangles.jpg', 'Solid Brass', 'Sizes: 2.4, 2.6, 2.8', 'Polish with brass cleaner.', 20, 4.6),
(58, 4, 5, 'Real Pressed Flower Resin Pendant', 'Oval glass resin pendant containing real dried wildflowers on a sterling silver chain.', 899.00, '/images/products/jewelry-pressed-flower-pendant.jpg', 'Clear Resin & Real Botanical', '45cm silver chain', 'Keep out of direct sunlight.', 13, 4.9),
(59, 1, 5, 'Blue Pottery Ceramic Bead Necklace', 'Hand-painted blue pottery ceramic spherical beads strung with lapis blue glass beads.', 999.00, '/images/products/jewelry-blue-pottery-necklace.jpg', 'Quartz Pottery Beads & Silver wire', '50cm length', 'Handle ceramic beads gently.', 12, 4.8),
(60, 5, 5, 'Jaipur Meenakari Peacock Anklet Pair', 'Pair of traditional silver-plated payal anklets decorated with colorful peacock enamel.', 849.00, '/images/products/jewelry-meenakari-peacock-anklet.jpg', 'Silver-plated alloy & enamel', '26cm length + extension', 'Store in ziplock pouch.', 17, 4.7),
(61, 3, 6, 'Hand-Carved Sheesham Wood Jewelry Box', 'Solid sheesham wooden keepsake box featuring detailed floral brass wire inlay on lid.', 1249.00, '/images/products/gifts-carved-wooden-jewelry-box.jpg', 'Rosewood with brass wire inlay', '20cm x 12cm x 8cm', 'Wipe with dry cloth.', 12, 4.9),
(62, 1, 6, 'Blue Pottery Hand-Painted Photo Frame', 'Jaipur blue pottery tabletop picture frame designed for 4x6 inch memories.', 999.00, '/images/products/gifts-blue-pottery-photo-frame.jpg', 'Ceramic Quartz & Glass', 'Outer: 22cm x 17cm', 'Clean glass with microfiber cloth.', 14, 4.8),
(63, 5, 6, 'Moradabad Engraved Brass Pen Stand', 'Heavy brass cylindrical desk holder intricately hand-etched with Mughal floral vines.', 1199.00, '/images/products/gifts-engraved-brass-pen-stand.jpg', 'Cast Solid Brass', '12cm height x 8cm diameter', 'Polish with brass cleaner.', 10, 4.8),
(64, 3, 6, 'Handcrafted Leather Journal Deckle Paper', 'Refillable leather notebook with 200 pages of handmade recycled cotton deckle edge paper.', 899.00, '/images/products/gifts-leather-deckle-journal.jpg', 'Genuine Leather & Cotton Paper', 'A5 size (21cm x 15cm)', 'Keep dry.', 18, 4.9),
(65, 3, 6, 'Soapstone Hand-Carved Aroma Oil Burner', 'Jali lattice carved soapstone essential oil burner diffuser with brass dish.', 749.00, '/images/products/gifts-soapstone-aroma-burner.jpg', 'Natural Soft Soapstone', '11cm height x 9cm diameter', 'Wipe dish after oil use.', 16, 4.7),
(66, 3, 6, 'Bidriware Silver Inlaid Keepsake Box', 'Black zinc-copper alloy trinket box embellished with intricate hand-hammered silver wire.', 2199.00, '/images/products/gifts-bidriware-keepsake-box.jpg', 'Bidri Alloy & Pure Silver Inlay', '12cm x 8cm x 5cm', 'Apply coconut oil to preserve patina.', 6, 5.0),
(67, 8, 6, 'Madhubani Wooden Tray & Coaster Set', 'Serving tray paired with 4 coasters, hand-painted with Madhubani peacock art.', 1599.00, '/images/products/gifts-madhubani-wooden-tray.jpg', 'Mango Wood & Protective Lacquer', 'Tray: 35cm x 25cm', 'Wipe clean with damp cloth.', 9, 4.9),
(68, 1, 6, 'Hand-Poured Scented Beeswax Candle Set', 'Gift box of 3 pure beeswax votive candles scented with natural sandalwood and rose.', 899.00, '/images/products/gifts-beeswax-candle-set.jpg', '100% Pure Beeswax & Essential oils', 'Each candle: 100g', 'Burn within sight.', 15, 4.8),
(69, 10, 6, 'Pashmina Silk Embroidered Stole Gift Box', 'Luxury gift box containing a hand-embroidered silk-pashmina blend unisex stole.', 2999.00, '/images/products/gifts-pashmina-stole-gift-box.jpg', 'Silk Pashmina Wool', '200cm x 70cm', 'Dry clean only.', 5, 5.0),
(70, 3, 6, 'Carved Walnut Wood Dry Fruit Bowl', 'Hand-carved Kashmiri walnut wood bowl featuring 4 divided compartments and lid.', 1899.00, '/images/products/gifts-walnut-wood-dry-fruit-bowl.jpg', 'Solid Kashmiri Walnut Wood', '25cm diameter', 'Wipe clean with dry cloth.', 8, 4.9),
(71, 3, 6, 'Brass Vintage Compass in Wooden Box', 'Functional nautical brass pocket compass presented in a velvet-lined carved wooden case.', 1399.00, '/images/products/gifts-brass-nautical-compass.jpg', 'Solid Brass & Rosewood box', 'Compass: 6cm, Box: 9cm', 'Avoid water exposure.', 11, 4.8),
(72, 1, 6, 'Terracotta Diya & Spice Box Set', 'Decorative gift hamper box with 4 hand-painted terracotta oil lamps and brass spice tin.', 999.00, '/images/products/gifts-terracotta-diya-spice-box.jpg', 'Clay & Brass', 'Hamper box: 25cm x 25cm', 'Handle clay diya carefully.', 13, 4.7),
(73, 8, 7, 'Authentic Madhubani Tree of Life Canvas', 'Hand-painted folk art canvas depicting the eternal Tree of Life with birds and flora.', 2499.00, '/images/products/art-madhubani-tree-of-life.jpg', 'Handmade Canvas & Acrylic/Natural Ink', '60cm x 45cm (Framed)', 'Keep out of direct sunlight. Dust lightly.', 8, 5.0),
(74, 4, 7, 'Warli Tribal Village Celebration Canvas', 'Traditional Maharashtra Warli monochromatic painting on rustic red ochre canvas.', 1799.00, '/images/products/art-warli-village-canvas.jpg', 'Rice paste pigment on cloth canvas', '50cm x 40cm (Unframed)', 'Frame under glass for protection.', 11, 4.8),
(75, 8, 7, 'Odisha Pattachitra Scroll Art Jagannath', 'Intricate cloth scroll painting depicting Lord Jagannath painted with mineral colors.', 2899.00, '/images/products/art-pattachitra-jagannath-scroll.jpg', 'Cotton canvas coated with gum & chalk', '75cm x 30cm', 'Keep dry.', 6, 4.9),
(76, 4, 7, 'Tanjore Gold Leaf Painting of Lakshmi', 'Rich South Indian Tanjore artwork embellished with 22k gold foil and semi-precious gems.', 4999.00, '/images/products/art-tanjore-gold-leaf-lakshmi.jpg', 'Teakwood board, Gold foil & Glass beads', '40cm x 30cm (Framed)', 'Dust glass frame carefully.', 4, 5.0),
(77, 3, 7, 'Hand-Carved Teakwood Relief Wall Panel', '3D wooden wall relief carved with lotus flowers and peacock pairs from a single wood block.', 3499.00, '/images/products/art-teakwood-relief-wall-panel.jpg', 'Reclaimed Teakwood', '60cm x 30cm x 4cm', 'Apply wood wax polish annually.', 5, 4.9),
(78, 4, 7, 'Rajasthani Pichwai Lotus Canvas Painting', 'Nathdwara style Pichwai wall canvas featuring pink lotus blooms and holy cows.', 2299.00, '/images/products/art-pichwai-lotus-canvas.jpg', 'Cotton Canvas & Watercolors', '60cm x 60cm', 'Keep away from moisture.', 9, 4.8),
(79, 4, 7, 'Gond Art Wildlife Canvas Peacock & Deer', 'Madhya Pradesh Gond tribal painting filled with intricate line and dot patterns.', 1999.00, '/images/products/art-gond-wildlife-canvas.jpg', 'Canvas & Acrylic colors', '50cm x 40cm', 'Dust gently with dry cloth.', 10, 4.9),
(80, 8, 7, 'Phad Folk Painting Royal Procession', 'Rajasthan Phad scroll painting depicting a royal king''s procession on horses and elephants.', 2699.00, '/images/products/art-phad-royal-procession.jpg', 'Handspun Khadi Canvas', '90cm x 35cm', 'Store unrolled or framed.', 7, 4.9),
(81, 1, 7, 'Terracotta Hand-Sculpted Wall Mask', 'Tribal face mask hand-moulded from red clay and hand-painted with earthen pigments.', 1199.00, '/images/products/art-terracotta-wall-mask.jpg', 'Baked Terracotta Clay', '30cm height x 18cm width', 'Mount securely on wall hook.', 12, 4.7),
(82, 4, 7, 'Cheriyal Scroll Miniature Painting', 'Telangana folk art painting on treated cloth portraying village stories.', 1899.00, '/images/products/art-cheriyal-miniature-scroll.jpg', 'Treated Khadi cloth & Natural dyes', '45cm x 30cm', 'Keep away from direct sunlight.', 8, 4.8),
(83, 4, 7, 'Kalamkari Tree of Knowledge Wall Hanging', 'Hand-painted cotton wall scroll created using bamboo pen and natural vegetable dyes.', 1699.00, '/images/products/art-kalamkari-wall-hanging.jpg', '100% Cotton & Natural Dyes', '100cm x 65cm', 'Dry clean only.', 14, 4.8),
(84, 4, 7, 'Kalighat Style Folk Art Canvas Frame', 'Bold line watercolor painting inspired by 19th-century Bengal Kalighat temple art.', 1499.00, '/images/products/art-kalighat-folk-art-canvas.jpg', 'Handmade Paper & Watercolors', '40cm x 30cm (Framed)', 'Handle glass frame carefully.', 13, 4.7),
(85, 3, 8, 'Shantiniketan Embossed Leather Tote Bag', 'Spacious leather shoulder tote embossed with traditional West Bengal batik floral art.', 2499.00, '/images/products/bags-shantiniketan-leather-tote.jpg', 'Vegetable-tanned Leather', '38cm x 30cm x 12cm', 'Condition with leather cream.', 10, 4.9),
(86, 9, 8, 'Hand-Embroidered Kutch Zipper Clutch', 'Ethnic pouch clutch embellished with dense colorful embroidery and mirrorwork.', 899.00, '/images/products/bags-kutch-zipper-clutch.jpg', 'Cotton Fabric & Glass Mirrors', '24cm x 14cm', 'Dry clean only.', 18, 4.8),
(87, 2, 8, 'Natural Jute & Leather Messenger Bag', 'Sturdy laptop messenger bag crafted from eco jute canvas with genuine leather trim.', 1899.00, '/images/products/bags-jute-leather-messenger.jpg', 'Eco Jute & Full-grain Leather', '40cm x 30cm x 8cm', 'Spot clean canvas.', 12, 4.7),
(88, 7, 8, 'Banjara Boho Tribal Patchwork Sling', 'One-of-a-kind vintage cotton patchwork crossbody bag with coin tassles.', 1299.00, '/images/products/bags-banjara-patchwork-sling.jpg', 'Vintage Cotton & Brass Coins', '28cm x 22cm, Strap 120cm', 'Hand wash cold gently.', 14, 4.8),
(89, 9, 8, 'Kalamkari Hand-Block Canvas Tote Bag', 'Eco-friendly reusable shopping tote bag featuring hand-printed Kalamkari bootis.', 799.00, '/images/products/bags-kalamkari-canvas-tote.jpg', '100% Heavy Cotton Canvas', '40cm x 35cm', 'Machine wash cold inside out.', 22, 4.7),
(90, 2, 8, 'Handcrafted Bamboo Rigid Handbag', 'Structured box handbag hand-woven from natural bamboo splits with wooden handle.', 1699.00, '/images/products/bags-bamboo-rigid-handbag.jpg', 'Natural Bamboo & Wood', '24cm x 18cm x 10cm', 'Keep dry.', 9, 4.9),
(91, 2, 8, 'Hand-Woven Macrame Boho Crossbody Sling', 'Bohemian macrame camera bag knotted from natural cream cotton yarn.', 1199.00, '/images/products/bags-macrame-crossbody-sling.jpg', '100% Natural Cotton Cord', '22cm x 18cm', 'Hand wash cold water.', 16, 4.8),
(92, 7, 8, 'Banarasi Brocade Potli Evening Bag', 'Festive drawstring handbag made of gold Banarasi brocade fabric with pearl handle.', 999.00, '/images/products/bags-banarasi-brocade-potli.jpg', 'Zari Brocade & Faux Pearls', '20cm x 18cm', 'Spot clean only.', 15, 4.8),
(93, 4, 8, 'Hand-Painted Madhubani Leather Wallet', 'Slim bi-fold men''s/unisex leather wallet adorned with hand-painted fish motifs.', 999.00, '/images/products/bags-madhubani-leather-wallet.jpg', 'Genuine Goat Leather', '11cm x 9cm closed', 'Do not rub painted area.', 17, 4.9),
(94, 2, 8, 'Palm Leaf Woven Market Basket Tote', 'Structured eco-friendly shopping basket woven from sturdy dried palm leaves.', 849.00, '/images/products/bags-palm-leaf-woven-basket.jpg', 'Dried Natural Palm Leaves', '35cm x 28cm x 15cm', 'Wipe clean with damp cloth.', 20, 4.6),
(95, 7, 8, 'Kantha Stitch Denim Travel Pouch', 'Upcycled denim toiletries pouch decorated with running Kantha embroidery.', 649.00, '/images/products/bags-kantha-denim-travel-pouch.jpg', 'Upcycled Denim & Cotton Thread', '22cm x 14cm x 8cm', 'Machine wash cold.', 24, 4.7),
(96, 7, 8, 'Raw Silk Envelope Clutch Zardozi', 'Sophisticated evening envelope clutch bag featuring hand-stitched gold wire Zardozi.', 1499.00, '/images/products/bags-raw-silk-zardozi-clutch.jpg', 'Pure Raw Silk & Metallic Wire', '26cm x 15cm', 'Dry clean only.', 11, 4.9);

-- 5. REVIEWS
INSERT INTO reviews (id, user_id, product_id, rating, review_text) VALUES
(1, 2, 1, 5, 'Exceptional craftsmanship! The mirror embroidery is very fine and fabric feels premium.'),
(2, 3, 2, 5, 'Extremely durable leather folio with rich embossing. Arrived quickly in eco packaging.'),
(3, 2, 13, 5, 'The Kanjeevaram silk weave is breathtaking! Stunning gold zari details.'),
(4, 3, 25, 5, 'Perfect eco-friendly toy for my toddler. Natural finish and smooth edges.'),
(5, 2, 37, 5, 'The blue pottery vase adds incredible royal charm to my living room desk.'),
(6, 3, 49, 5, 'Intricate filigree silver necklace. Recipient loved it as an anniversary gift.'),
(7, 2, 61, 5, 'Beautiful solid sheesham jewelry box. Fine brass inlay work.'),
(8, 3, 73, 5, 'Magnificent Madhubani painting on canvas! Beautiful vibrant colors.'),
(9, 2, 85, 5, 'High quality embossed leather tote bag. Very spacious and durable.');